### ISSUE TITLE
Make unit tests

### ISSUE THREAD

**Issue by Levasseur-Sp** [decathloncanada/data-utils#8]
## Code coverage
I may be aiming for 80% code coverage as it seems like a good amount!
I'd like to discuss it with you, since you have more experience than me in this! How attainable is 80% and should I aim lower/higher? @CaioBianchi @arthtux @sderrico

**Comment by sderrico** [comment]
Currently, we are at 1% in community project and I attest multiple projects where 100% was technically impossible. So I have the same goals: 80%. I previously sat down with some devs from others companies and 80% was the most popular, 1-2 guys was aiming 90% .

**Comment by Levasseur-Sp** [comment]
> Currently, we are at 1% in community project and I attest multiple projects where 100% was technically impossible. So I have the same goals: 80%. I previously sat down with some devs from others companies and 80% was the most popular, 1-2 guys was aiming 90% .

That's good to hear! 80% it is! What do the rest of you think?

**Comment by sderrico** [comment]
Differents reasons:
-  often, I do not see how to test some ui optimization
- testing async stuff can also be hard
- sometime, I felt some tests may take more  time to develop then getting the benefit
- mocking a lot of dependencies can be depressing
...
